-- 코드를 작성해주세요
SELECT T2.ID, IFNULL(T1.CHILD_COUNT, 0) AS "CHILD_COUNT"
FROM (
    SELECT PARENT_ID, COUNT(ID) AS "CHILD_COUNT"
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID
) T1 RIGHT JOIN ECOLI_DATA T2 ON T1.PARENT_ID = T2.ID
ORDER BY T2.ID;


/*
1 -> 1
2 -> 2
3 -> 0
4 -> 1
*/