-- 30일 대여 시 CAR_TYPE 별 할인 정보
WITH DISCOUNT AS (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE LIKE '%30%'
),
-- 11월 1일 ~ 11월 30일 대여 불가능한 CAR_ID
RENTAL_DISABLE AS (
    SELECT DISTINCT(CAR_ID)
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-11-01' AND '2022-11-30'
        OR END_DATE BETWEEN '2022-11-01' AND '2022-11-30'
        OR (START_DATE < '2022-11-01' AND END_DATE > '2022-11-30')
),
-- CAR_ID 별 30일 대여 시 금액
DAY30_FEE AS (
    SELECT C.CAR_ID, FLOOR(C.DAILY_FEE * (1 - D.DISCOUNT_RATE/100) * 30) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR C
        JOIN DISCOUNT D ON C.CAR_TYPE = D.CAR_TYPE
)

SELECT T1.CAR_ID, T1.CAR_TYPE, T2.FEE
FROM CAR_RENTAL_COMPANY_CAR T1
    JOIN DAY30_FEE T2 ON T1.CAR_ID = T2.CAR_ID
WHERE T1.CAR_TYPE IN ('세단', 'SUV')
    AND T1.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM RENTAL_DISABLE
    )
    AND (T2.FEE >= 500000 AND T2.FEE < 2000000)
ORDER BY T2.FEE DESC, T1.CAR_TYPE, T1.CAR_ID DESC;