-- 코드를 작성해주세요
SELECT COUNT(T1.ID) AS FISH_COUNT, MIN(T2.FISH_NAME) AS FISH_NAME
FROM FISH_INFO T1 
JOIN FISH_NAME_INFO T2 ON T1.FISH_TYPE = T2.FISH_TYPE
GROUP BY T1.FISH_TYPE
ORDER BY FISH_COUNT DESC;