-- 코드를 작성해주세요
SELECT T1.QUARTER, COUNT(T1.ID) AS 'ECOLI_COUNT'
FROM (
    SELECT ID,
        CASE WHEN MONTH(DIFFERENTIATION_DATE) <= 3 THEN '1Q'
            WHEN MONTH(DIFFERENTIATION_DATE) <= 6 THEN '2Q'
            WHEN MONTH(DIFFERENTIATION_DATE) <= 9 THEN '3Q'
            ELSE '4Q' END AS 'QUARTER'
    FROM ECOLI_DATA
) T1
GROUP BY T1.QUARTER
ORDER BY T1.QUARTER;
