-- 코드를 입력하세요
/*
2022년 10월 16일에 대여 중이다.
=> START_DATE <= 2022.10.16 <= END_DATE
*/

SELECT T.CAR_ID, 
       CASE WHEN MIN(T.AVAILABILITY) = 0 THEN '대여중'
            ELSE '대여 가능' END AS AVAILABILITY 
FROM (
    SELECT CAR_ID,
           CASE WHEN START_DATE <= '2022-10-16' AND END_DATE >= '2022.10.16' THEN 0
                ELSE 1 END AS AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) T
GROUP BY T.CAR_ID
ORDER BY T.CAR_ID DESC
