-- 코드를 작성해주세요
WITH TEMP AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS 'YEAR', MAX(SIZE_OF_COLONY) AS 'MAX_SIZE'
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)    
)
SELECT T1.YEAR, T1.MAX_SIZE - T2.SIZE_OF_COLONY AS 'YEAR_DEV', T2.ID
FROM TEMP T1
    JOIN ECOLI_DATA T2 ON T1.YEAR = YEAR(T2.DIFFERENTIATION_DATE)
ORDER BY T1.YEAR, YEAR_DEV;