-- 코드를 작성해주세요
SELECT T1.ID, T2.FISH_NAME, T1.LENGTH
FROM FISH_INFO T1
    JOIN FISH_NAME_INFO T2 ON T1.FISH_TYPE = T2.FISH_TYPE
WHERE (T1.FISH_TYPE, T1.LENGTH) IN (
    SELECT T3.FISH_TYPE, MAX(T3.LENGTH)
    FROM FISH_INFO T3
    GROUP BY T3.FISH_TYPE
)
ORDER BY T1.ID;