-- 코드를 입력하세요
SELECT DISTINCT RC.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR RC
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY RH ON RC.CAR_ID = RH.CAR_ID
WHERE RC.CAR_TYPE = '세단' AND MONTH(RH.START_DATE) = 10
ORDER BY RC.CAR_ID DESC